spring:
  main:
    banner-mode: console
  application:
    name: demo_turbine

server:
  port: 8085
eureka:
  client:
   serviceUrl:
    defaultZone: http://localhost:8761/eureka/

turbine:
  aggregator:
    cluster-config: default
  app-config: eureka_client_01,eureka_client_02
  cluster-name-expression: "'default'"


