### banner显示模式，可选值[log|console|false]
spring:
  main:
    banner-mode: console
  application:
    name: eureka_client_01

server:
  port: 8081
eureka:
  client:
   serviceUrl:
    defaultZone: http://localhost:8761/eureka/

management:
  server:
    port: 9001
  endpoints:
    web:
   #   base-path: / #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      exposure:
        include: '*'  #开放所有页面节点  默认只开启了health、info两个节点