
server:
  port: 8761
  servlet:
    application-display-name: eureka_server
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    service-url:
      defaulZone: http://localhost:8761/eureka/
spring:
  application:
    name: eureka_server
management:
  endpoints:
    web:
      exposure:
        include: "*"