spring:
  main:
    banner-mode: console
  application:
    name: demo_hystrix

server:
  port: 8084
eureka:
  client:
   serviceUrl:
    defaultZone: http://localhost:8761/eureka/
management:
  server:
    port: 9003
  endpoints:
    web:
      exposure:
        include: "*"
